# Generated by Django 4.2.4 on 2023-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('date_available', models.DateField()),
                ('resume', models.FileField(upload_to='resumes')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
