# Generated by Django 4.2.4 on 2023-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='live_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
