# Generated by Django 4.2.6 on 2023-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_portfolioproject_live_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='score',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_key',
            field=models.BooleanField(default=False, verbose_name='is_key'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
