# Generated by Django 4.2.6 on 2023-10-10 22:24

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_remove_skill_score_alter_skill_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_key',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.CreateModel(
            name='SkillTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='skills')),
                ('is_key', models.BooleanField(default=False)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_site.skill')),
            ],
            options={
                'verbose_name': 'Skill Translation',
                'db_table': 'main_site_skill_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
