# Generated by Django 4.2.6 on 2023-10-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_skill_image_remove_skill_is_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skilltranslation',
            name='is_key',
        ),
    ]
