# Generated by Django 4.2.6 on 2023-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_remove_skilltranslation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltranslation',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AddField(
            model_name='skilltranslation',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
    ]
