# Generated by Django 4.2.6 on 2023-10-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_remove_userprofile_avatar_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofiletranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofiletranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='userprofiletranslation',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofiletranslation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfileTranslation',
        ),
    ]
