# Generated by Django 4.2.6 on 2023-10-11 04:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_alter_userprofiletranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'verbose_name': 'Portfolio Project', 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='source_code_url',
        ),
        migrations.CreateModel(
            name='PortfolioProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('date', models.DateTimeField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_code_url', models.CharField(blank=True, max_length=100, null=True)),
                ('live_url', models.CharField(blank=True, max_length=100, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_site.portfolioproject')),
            ],
            options={
                'verbose_name': 'Portfolio Project Translation',
                'db_table': 'main_site_portfolioproject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
