# Generated by Django 4.2.6 on 2023-10-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_alter_portfolioproject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprojecttranslation',
            name='date',
        ),
    ]
