# Generated by Django 4.2.6 on 2023-10-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_image_alter_skilltranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_site.portfolioproject'),
        ),
    ]
