# Generated by Django 4.2.6 on 2023-11-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_imagetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_site.portfolioproject'),
        ),
    ]
