# Generated by Django 4.2.6 on 2023-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_remove_imagetranslation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetranslation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='imagetranslation',
            name='caption',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioprojecttranslation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='siteownertranslation',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
