# Generated by Django 4.2.6 on 2023-12-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteownertranslation',
            name='site_blurb',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
